name: publish-staging-docs

on: [workflow_dispatch]

permissions:
  contents: write
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sphinx build
        run: sphinx-build doc _build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2      
      - name: Deploy to S3 Staging bucket - rate-plan-documentation-staging
        run: |
            aws s3 rm s3://rate-plan-documentation-staging --recursive
            aws s3 sync _build s3://rate-plan-documentation-staging --exclude rate-plan-schema-docs